[package]
name = "erlust"
version = "0.3.1"
authors = ["Alexey Voznyuk <me@swizard.info>"]
description = "Erlang-inspired framework for organizing async code in a fault-tolerant way"
edition = "2018"

[dependencies]
log = "0.4"
tokio = "0.1"
futures = "0.1"

[dev-dependencies]
tokio-codec = "0.1"
pretty_env_logger = "0.2"
