[package]
name = "erlust"
version = "0.1.11"
authors = ["Alexey Voznyuk <me@swizard.info>"]
description = "Erlang-inspired framework for organizing async code in a fault-tolerant way"
edition = "2018"

[dependencies]
log = "0.4"
tokio = "0.1"
futures = "0.1"
